const AIRLINE_NAMES: Record<string, string> = {
  BA: "British Airways",
  AF: "Air France",
  LH: "Lufthansa",
  KL: "KLM",
  EK: "Emirates",
  QR: "Qatar Airways",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  TK: "Turkish Airlines",
  AA: "American Airlines",
  UA: "United Airlines",
  DL: "Delta Air Lines",
  AC: "Air Canada",
  QF: "Qantas",
  EY: "Etihad Airways",
  NH: "ANA",
  JL: "Japan Airlines",
  IB: "Iberia",
  AZ: "ITA Airways",
  LX: "Swiss International",
  OS: "Austrian Airlines",
  SK: "SAS",
  AY: "Finnair",
  TP: "TAP Air Portugal",
  FR: "Ryanair",
  U2: "easyJet",
  WN: "Southwest Airlines",
  B6: "JetBlue",
  VS: "Virgin Atlantic",
  EI: "Aer Lingus",
  SU: "Aeroflot",
  MU: "China Eastern",
  CA: "Air China",
  KE: "Korean Air",
  TG: "Thai Airways",
  MH: "Malaysia Airlines",
  GA: "Garuda Indonesia",
  AI: "Air India",
  WY: "Oman Air",
  GF: "Gulf Air",
  MS: "EgyptAir",
  SA: "South African Airways",
  LA: "LATAM Airlines",
  AV: "Avianca",
  CM: "Copa Airlines",
};

export function airlineName(code: string): string {
  return AIRLINE_NAMES[code.toUpperCase()] || code.toUpperCase();
}
